const GET_ALL_CATEGORIES_BEGIN = "GET_ALL_CATEGORIES_BEGIN";
const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";
const GET_CATEGORY_BY_NAME_BEGIN = "GET_CATEGORY_BY_NAME_BEGIN";
const GET_CATEGORY_BY_NAME_SUCCESS = "GET_CATEGORY_BY_NAME_SUCCESS";
const GET_CATEGORY_BY_NAME_FAILURE = "GET_CATEGORY_BY_NAME_FAILURE";

export {
  GET_ALL_CATEGORIES_BEGIN,
  GET_ALL_CATEGORIES_SUCCESS,
  GET_ALL_CATEGORIES_FAILURE,
  GET_CATEGORY_BY_NAME_BEGIN,
  GET_CATEGORY_BY_NAME_SUCCESS,
  GET_CATEGORY_BY_NAME_FAILURE,
};
