const GET_ALL_PRODUCTS_BEGIN = "GET_ALL_PRODUCTS_BEGIN";
const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";
const GET_PRODUCT_BY_ID_BEGIN = "GET_PRODUCT_BY_ID";
const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";
const ADD_PRODUCT_BEGIN = "ADD_PRODUCT_BEGIN";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";
const UPDATE_PRODUCT_BEGIN = "UPDATE_PRODUCT_BEGIN";
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";
const DELETE_PRODUCT_BEGIN = "DELETE_PRODUCT_BEGIN";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
const GET_ALL_PRODUCTS_BY_CATEGORY_BEGIN = "GET_ALL_PRODUCTS_BY_CATEGORY_BEGIN";
const GET_ALL_PRODUCTS_BY_CATEGORY_SUCCESS =
  "GET_ALL_PRODUCTS_BY_CATEGORY_SUCCESS";
const GET_ALL_PRODUCTS_BY_CATEGORY_FAILURE =
  "GET_ALL_PRODUCTS_BY_CATEGORY_FAILURE";

export {
  GET_ALL_PRODUCTS_BEGIN,
  GET_ALL_PRODUCTS_SUCCESS,
  GET_ALL_PRODUCTS_FAILURE,
  GET_PRODUCT_BY_ID_BEGIN,
  GET_PRODUCT_BY_ID_SUCCESS,
  GET_PRODUCT_BY_ID_FAILURE,
  ADD_PRODUCT_BEGIN,
  ADD_PRODUCT_SUCCESS,
  ADD_PRODUCT_FAILURE,
  UPDATE_PRODUCT_BEGIN,
  UPDATE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_FAILURE,
  DELETE_PRODUCT_BEGIN,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_FAILURE,
  GET_ALL_PRODUCTS_BY_CATEGORY_BEGIN,
  GET_ALL_PRODUCTS_BY_CATEGORY_SUCCESS,
  GET_ALL_PRODUCTS_BY_CATEGORY_FAILURE,
};
