const GET_USER_CART = "GET_USER_CART";
const GET_USER_CART_SUCCESS = "GET_USER_CART_SUCCESS";
const GET_USER_CART_FAILURE = "GET_USER_CART_FAILURE";
const GET_CART_BY_DATE = "GET_CART_BY_DATE";
const GET_CART_BY_DATE_SUCCESS = "GET_CART_BY_DATE_SUCCESS";
const GET_CART_BY_DATE_FAILURE = "GET_CART_BY_DATE_FAILURE";
const ADD_NEW_CART = "ADD_NEW_CART";
const ADD_NEW_CART_SUCCESS = "ADD_NEW_CART_SUCCESS";
const ADD_NEW_CART_FAILURE = "ADD_NEW_CART_FAILURE";
const UPDATE_CART = "UPDATE_CART";
const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
const UPDATE_CART_FAILURE = "UPDATE_CART_FAILURE";
const DELETE_CART = "DELETE_CART";
const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";
const GET_ALL_CART = "GET_ALL_CART";
const GET_ALL_CART_SUCCESS = "GET_ALL_CART_SUCCESS";
const GET_ALL_CART_FAILURE = "GET_ALL_CART_FAILURE";

export {
  GET_USER_CART,
  GET_USER_CART_SUCCESS,
  GET_USER_CART_FAILURE,
  GET_CART_BY_DATE,
  GET_CART_BY_DATE_SUCCESS,
  GET_CART_BY_DATE_FAILURE,
  ADD_NEW_CART,
  ADD_NEW_CART_SUCCESS,
  ADD_NEW_CART_FAILURE,
  UPDATE_CART,
  UPDATE_CART_SUCCESS,
  UPDATE_CART_FAILURE,
  DELETE_CART,
  DELETE_CART_SUCCESS,
  DELETE_CART_FAILURE,
  GET_ALL_CART,
  GET_ALL_CART_SUCCESS,
  GET_ALL_CART_FAILURE,
};
